name: management
description: "A new Flutter project."
version: 0.0.1
homepage:

executables:
  generate: generate

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: any
  flutter:
    sdk: flutter
  focus_detector: any
  get_it: any
  logger: any
  provider: any
  rx_shared_preferences: ^4.0.0
  rxdart: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
